// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using resumeSystem.Data;

#nullable disable

namespace resumeSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919131918_SeedDefaultAttributes")]
    partial class SeedDefaultAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("resumeSystem.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("resumeSystem.Domain.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<int>("DataTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<bool>("IsDisplay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_display");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DataTypeId");

                    b.ToTable("attributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DataTypeId = 1,
                            IsDisplay = true,
                            Title = "Любимый язык программирования"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DataTypeId = 2,
                            IsDisplay = true,
                            Title = "О себе"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DataTypeId = 3,
                            IsDisplay = true,
                            Title = "Количество лет опыта"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DataTypeId = 4,
                            IsDisplay = true,
                            Title = "Дата начала карьеры"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DataTypeId = 5,
                            IsDisplay = true,
                            Title = "Период работы"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DataTypeId = 6,
                            IsDisplay = true,
                            Title = "Готов к удалённой работе"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            DataTypeId = 7,
                            IsDisplay = true,
                            Title = "Уровень английского"
                        });
                });

            modelBuilder.Entity("resumeSystem.Domain.AttributeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.ToTable("attribute_options", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeId = 7,
                            Options = "A1"
                        },
                        new
                        {
                            Id = 2,
                            AttributeId = 7,
                            Options = "A2"
                        },
                        new
                        {
                            Id = 3,
                            AttributeId = 7,
                            Options = "B1"
                        },
                        new
                        {
                            Id = 4,
                            AttributeId = 7,
                            Options = "B2"
                        },
                        new
                        {
                            Id = 5,
                            AttributeId = 7,
                            Options = "C1"
                        },
                        new
                        {
                            Id = 6,
                            AttributeId = 7,
                            Options = "C2"
                        });
                });

            modelBuilder.Entity("resumeSystem.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDisplay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_display");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDisplay = true,
                            Title = "Общие"
                        });
                });

            modelBuilder.Entity("resumeSystem.Domain.CompareType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompareTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compare_type");

                    b.HasKey("Id");

                    b.ToTable("compare_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompareTypeName = "Equals"
                        },
                        new
                        {
                            Id = 2,
                            CompareTypeName = "Not equals"
                        },
                        new
                        {
                            Id = 3,
                            CompareTypeName = "Contains"
                        },
                        new
                        {
                            Id = 4,
                            CompareTypeName = "Greater than"
                        },
                        new
                        {
                            Id = 5,
                            CompareTypeName = "Less than"
                        },
                        new
                        {
                            Id = 6,
                            CompareTypeName = "Greater than or equal"
                        },
                        new
                        {
                            Id = 7,
                            CompareTypeName = "Less than or equal"
                        });
                });

            modelBuilder.Entity("resumeSystem.Domain.DataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_type");

                    b.HasKey("Id");

                    b.ToTable("data_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataTypeName = "String"
                        },
                        new
                        {
                            Id = 2,
                            DataTypeName = "Text"
                        },
                        new
                        {
                            Id = 3,
                            DataTypeName = "Number"
                        },
                        new
                        {
                            Id = 4,
                            DataTypeName = "Date"
                        },
                        new
                        {
                            Id = 5,
                            DataTypeName = "Period"
                        },
                        new
                        {
                            Id = 6,
                            DataTypeName = "Boolean"
                        },
                        new
                        {
                            Id = 7,
                            DataTypeName = "One of many"
                        });
                });

            modelBuilder.Entity("resumeSystem.Domain.DataTypeCompareType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompareTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("compare_type");

                    b.Property<int>("DataTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.HasKey("Id");

                    b.HasIndex("CompareTypeId");

                    b.HasIndex("DataTypeId");

                    b.ToTable("data_type_compare_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompareTypeId = 1,
                            DataTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompareTypeId = 2,
                            DataTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompareTypeId = 3,
                            DataTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompareTypeId = 1,
                            DataTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CompareTypeId = 2,
                            DataTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            CompareTypeId = 3,
                            DataTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            CompareTypeId = 1,
                            DataTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            CompareTypeId = 2,
                            DataTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            CompareTypeId = 4,
                            DataTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            CompareTypeId = 5,
                            DataTypeId = 3
                        },
                        new
                        {
                            Id = 11,
                            CompareTypeId = 6,
                            DataTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            CompareTypeId = 7,
                            DataTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            CompareTypeId = 1,
                            DataTypeId = 4
                        },
                        new
                        {
                            Id = 14,
                            CompareTypeId = 2,
                            DataTypeId = 4
                        },
                        new
                        {
                            Id = 15,
                            CompareTypeId = 4,
                            DataTypeId = 4
                        },
                        new
                        {
                            Id = 16,
                            CompareTypeId = 5,
                            DataTypeId = 4
                        },
                        new
                        {
                            Id = 17,
                            CompareTypeId = 6,
                            DataTypeId = 4
                        },
                        new
                        {
                            Id = 18,
                            CompareTypeId = 7,
                            DataTypeId = 4
                        },
                        new
                        {
                            Id = 19,
                            CompareTypeId = 1,
                            DataTypeId = 5
                        },
                        new
                        {
                            Id = 20,
                            CompareTypeId = 2,
                            DataTypeId = 5
                        },
                        new
                        {
                            Id = 21,
                            CompareTypeId = 4,
                            DataTypeId = 5
                        },
                        new
                        {
                            Id = 22,
                            CompareTypeId = 5,
                            DataTypeId = 5
                        },
                        new
                        {
                            Id = 23,
                            CompareTypeId = 6,
                            DataTypeId = 5
                        },
                        new
                        {
                            Id = 24,
                            CompareTypeId = 7,
                            DataTypeId = 5
                        },
                        new
                        {
                            Id = 25,
                            CompareTypeId = 1,
                            DataTypeId = 6
                        },
                        new
                        {
                            Id = 26,
                            CompareTypeId = 2,
                            DataTypeId = 6
                        },
                        new
                        {
                            Id = 27,
                            CompareTypeId = 1,
                            DataTypeId = 7
                        },
                        new
                        {
                            Id = 28,
                            CompareTypeId = 2,
                            DataTypeId = 7
                        });
                });

            modelBuilder.Entity("resumeSystem.Domain.RequiredUserAttributes", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("second_name");

                    b.HasKey("UserId");

                    b.ToTable("required_user_attributes", (string)null);
                });

            modelBuilder.Entity("resumeSystem.Domain.UserAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("UserId");

                    b.ToTable("user_attributes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("resumeSystem.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("resumeSystem.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("resumeSystem.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("resumeSystem.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("resumeSystem.Domain.Attribute", b =>
                {
                    b.HasOne("resumeSystem.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("resumeSystem.Domain.DataType", "DataType")
                        .WithMany()
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DataType");
                });

            modelBuilder.Entity("resumeSystem.Domain.AttributeOption", b =>
                {
                    b.HasOne("resumeSystem.Domain.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("resumeSystem.Domain.DataTypeCompareType", b =>
                {
                    b.HasOne("resumeSystem.Domain.CompareType", "CompareType")
                        .WithMany()
                        .HasForeignKey("CompareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("resumeSystem.Domain.DataType", "DataType")
                        .WithMany()
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompareType");

                    b.Navigation("DataType");
                });

            modelBuilder.Entity("resumeSystem.Domain.RequiredUserAttributes", b =>
                {
                    b.HasOne("resumeSystem.Domain.ApplicationUser", "User")
                        .WithOne("RequiredUserAttributes")
                        .HasForeignKey("resumeSystem.Domain.RequiredUserAttributes", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("resumeSystem.Domain.UserAttribute", b =>
                {
                    b.HasOne("resumeSystem.Domain.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("resumeSystem.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("resumeSystem.Domain.ApplicationUser", b =>
                {
                    b.Navigation("RequiredUserAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
